server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:mem:historial;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 2000
            read-timeout: 3000

banco:
  migracion:
    semana: semana_3

resilience4j:
  circuitbreaker:
    instances:
      cuentasClient:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 6
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
  retry:
    instances:
      cuentasClient:
        max-attempts: 3
        wait-duration: 300ms
        ignore-exceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
