server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:transacciones;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

banco:
  migracion:
    semana: semana_3     # semana_1 | semana_2 | semana_3 (dataset a migrar)

resilience4j:
  circuitbreaker:
    instances:
      resumen:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 6
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
  retry:
    instances:
      resumen:
        max-attempts: 3
        wait-duration: 300ms
        ignore-exceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
  ratelimiter:
    instances:
      resumen:
        limit-for-period: 20
        limit-refresh-period: 10s
        timeout-duration: 0
